<template>
  <div class="two-column-multi-select">
    <div class="two-column-multi-select__unselected-items">
      <div class="two-column-multi-select__column-header">
        <slot name="unselected-header">{{ unselectedHeader }}</slot>
      </div>
      <ul class="two-column-multi-select__item-list">
        <li v-if="filterable">
          <TextInput
            v-model.trim="filter"
            class="search-field"
            pre-icon="search"
            show-reset
          />
        </li>
        <li v-for="item in unselectedOptions" :key="item.value">
          <MultiSelectItem v-bind="item" :name="name" @input="handleInput" />
        </li>
      </ul>
    </div>
    <div class="two-column-multi-select__selected-items">
      <div class="two-column-multi-select__column-header">
        <slot name="selected-header">{{ selectedHeader }}</slot>
      </div>
      <ul class="two-column-multi-select__item-list">
        <li v-for="item in selectedOptions" :key="item.value">
          <MultiSelectItem
            v-bind="item"
            :name="name"
            checked
            @input="handleInput"
          />
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import shortid from 'shortid';
import MultiSelectItem from '../internal/TwoColumnMultiSelect/MultiSelectItem.vue';
import TextInput from '../TextInput/TextInput.vue';

/**
 * `import { TwoColumnMultiSelect } from '@bambeehr/pollen';`
 *
 * A UI component that is essentially a multi-select checkbox group. Unselected
 * items will display in the left column. Selected items will display in the
 * right column. Optionally, a search filter can be added to filter unselected
 * items based on case-insensitive string matching. Column headers can be
 * changed via props or slots.
 */
export default {
  components: { MultiSelectItem, TextInput },
  props: {
    /** If true, displays the search filter. */
    filterable: {
      type: Boolean,
      default: false,
    },
    /** An intial filter value to set. */
    initialFilter: {
      type: String,
      default: '',
    },
    /**
     * The shared name between checkox inputs. A random name is generated by
     * default.
     */
    name: {
      type: String,
      default: shortid.generate,
    },
    /**
     * Options are an array of objects with a `label`, `value`, and `icon`\
     * property. All are strings. Icon is optional.
     */
    options: {
      type: Array,
      default: () => [],
    },
    /** The header to display above the right column. Slots take precedence. */
    selectedHeader: {
      type: String,
      default: 'Selected',
    },
    /** The header to display above the left column. Slots take precedence. */
    unselectedHeader: {
      type: String,
      default: 'Options',
    },
    /**
     * Value of the input. This is an array of strings, the `value` of selected
     * `options` items.
     */
    value: {
      type: Array,
      default: () => [],
    },
  },
  data() {
    return {
      filter: this.initialFilter,
    };
  },
  computed: {
    selectedOptions() {
      // Using `map` rather than `filter` here preserves the order of `value`.
      return this.value.map((value) =>
        this.options.find((item) => item.value === value)
      );
    },
    unselectedOptions() {
      return this.options.filter(
        (item) =>
          !this.value.includes(item.value) &&
          (!this.filterable ||
            (this.filterable &&
              item.label
                .toLowerCase()
                .includes(this.filter.toLowerCase().trim())))
      );
    },
  },
  methods: {
    handleInput(e) {
      const { checked, value } = e.target;
      const newValue = checked
        ? [...this.value, value]
        : this.value.filter((item) => item !== value);
      this.$emit('input', newValue);
    },
  },
};
</script>

<style scoped>
.two-column-multi-select {
  @apply border
    border-gray-5
    flex
    /* For legacy */
    border-solid;
}

.two-column-multi-select__unselected-items,
.two-column-multi-select__selected-items {
  @apply flex flex-col flex-grow w-1/2;
}

.two-column-multi-select__unselected-items {
  @apply border-r
    border-gray-5
    /* For legacy */
    border-b-0
    border-l-0
    border-t-0
    border-solid;
}

.two-column-multi-select__item-list {
  @apply flex-grow
    overflow-auto
    /* For legacy */
    list-none
    m-0
    p-0;
}

.two-column-multi-select__column-header {
  @apply border-b
    border-gray-5
    font-body-small
    font-semibold
    px-6
    py-3
    /* For legacy */
    border-l-0
    border-r-0
    border-t-0
    border-solid;
}

.two-column-multi-select .search-field {
  @apply m-2;
}
</style>
