<template>
  <div
    class="toggle-group"
    :class="[
      vertical ? 'toggle-group--vertical' : 'toggle-group--horizontal',
      `toggle-group--${size}`,
    ]"
  >
    <component
      :is="component"
      v-for="(item, i) in mappedOptions"
      :id="`${name}-${i}`"
      :key="item.value"
      v-bind="getInputProps(item)"
      @input="handleInput(item.value, $event)"
    />
  </div>
</template>

<script>
import shortid from 'shortid';
import Form from '../../../../constants/Form';
import CheckboxInput from '../../../CheckboxInput/CheckboxInput.vue';
import RadioInput from '../../../RadioInput/RadioInput.vue';
import SwitchInput from '../../../SwitchInput/SwitchInput.vue';
import mapOptions from '../../../../util/mapOptions';

const ToggleTypes = Object.freeze({
  CHECKBOX: 'checkbox',
  RADIO: 'radio',
  SWITCH: 'switch',
});

const ToggleComponents = Object.freeze({
  [ToggleTypes.CHECKBOX]: CheckboxInput,
  [ToggleTypes.RADIO]: RadioInput,
  [ToggleTypes.SWITCH]: SwitchInput,
});

export default {
  props: {
    /** If the input is disabled. */
    disabled: {
      type: Boolean,
      default: false,
    },
    /**
     * If true, this field will display in an error state.
     */
    invalid: {
      type: Boolean,
      default: false,
    },
    /** Whether labels should display to the `left` or `right` of the radio. */
    labelPosition: {
      type: String,
      default: Form.LabelPositions.RIGHT,
      validator: (value) => Object.values(Form.LabelPositions).includes(value),
    },
    /**
     * The shared name between radio inputs. A random name is generated by
     * default.
     */
    name: {
      type: String,
      default: shortid.generate,
    },
    /**
     * The available options for this component. This is an array of values.
     * Each individual value can be either a string, or an object with a `label`
     * and `value` key. The `label` is what the user sees. The `value` is what
     * will be emitted as an `input` event.
     */
    options: {
      type: Array,
      default: () => [],
    },
    /** If the input is disabled. */
    required: {
      type: Boolean,
      default: false,
    },
    /** One of `dense`, or `normal`. */
    size: {
      type: String,
      default: Form.Sizes.NORMAL,
      validator: (value) =>
        [Form.Sizes.DENSE, Form.Sizes.NORMAL].includes(value),
    },
    /** If true, displays radio options vertically. */
    vertical: {
      type: Boolean,
      default: false,
    },
    /**
     * Value of the input. Compatible with `v-model`. If this is a `radio` group
     * then value should be a string, otherwise this is an array.
     */
    value: {
      type: [String, Array],
      default: null,
    },
    /** Toggle type. One of `checkbox`, `radio`, or `switch`. */
    type: {
      type: String,
      default: ToggleTypes.CHECKBOX,
      validator: (value) => Object.values(ToggleTypes).includes(value),
    },
    /**
     * One of `standard` or `raised`.
     */
    variant: {
      type: String,
      default: Form.Variants.STANDARD,
      validator: (value) =>
        [Form.Variants.STANDARD, Form.Variants.RAISED].includes(value),
    },
  },
  computed: {
    component() {
      return ToggleComponents[this.type];
    },
    isMulti() {
      return this.type !== ToggleTypes.RADIO;
    },
    mappedOptions() {
      return mapOptions(this.options);
    },
  },
  methods: {
    getInputProps(item) {
      const props = {
        disabled: this.disabled,
        invalid: this.invalid,
        label: item.label,
        labelPosition: this.labelPosition,
        name: this.name,
        required: this.required,
        size: this.size,
        variant: this.variant,
      };

      if (this.isMulti) {
        props.value = (this.value || []).includes(item.value);
      } else {
        props.checked = this.value === item.value;
        props.value = item.value;
      }
      return props;
    },
    handleInput(val, isChecked) {
      let emittedValue = val;
      if (this.isMulti) {
        emittedValue = isChecked
          ? [...(this.value || []), val]
          : this.value.filter((item) => item !== val);
      }
      this.$emit('input', emittedValue);
    },
  },
};
</script>

<style scoped>
.toggle-group {
  @apply inline-flex items-start;
}

.toggle-group.toggle-group--vertical {
  @apply flex-col items-stretch;
}

.toggle-group--dense {
  @apply -m-2;
}

.toggle-group--dense .toggle-input {
  @apply m-2;
}

.toggle-group--normal {
  @apply -m-3;
}

.toggle-group--normal .toggle-input {
  @apply m-3;
}

/* .toggle-group--large {
  @apply -m-4;
}

.toggle-group--large .toggle-input {
  @apply m-4;
} */
</style>
